const INTERNAL_SERVER_STATUS_CODE = 500;

enum HttpStatusCode {
	OK = 200,
	CREATED = 201,
	BAD_REQUEST = 400,
	NOT_FOUND = 404,
	CONFLICT = 409,
	UNPROCESSABLE_ENTITY = 422,
	INTERNAL_SERVER_ERROR = INTERNAL_SERVER_STATUS_CODE,
}

export { HttpStatusCode };
